# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CS 230 Operating Platforms
email: eduardo@eduardo.host
description: >- # this means to ignore newlines until "baseurl:"
 The course had us contribute to a software design description based on some starter code that we had to refactor
 to align it with the client's request. Being an open ended assignment; I figured it'd be best to presume that the client was
 willing to work with a platform like unity to make their code more platform agnostic and ready to be deployed where the market takes them. 
 The course made me appreciate how engineers have to choose the right tool for the job. The course had us work with APIs using DropWizard and learning how to orchestrate 
 build using Maven. It was an excellent pairing with CS320, Software Testing and Quality Assurance; and is making an awesome segue into the next term's coursework in Software
 Security.

baseurl: "/CS-230-Operting-Platforms" # the subpath of your site, e.g. /blog
domain: eduardodothost.github.io
url: https://eduardodothost.github.io/CS-230-Operting-Platforms/ # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: eduardodothost
github_username:  eduardodothost

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
